name: Arch Linux CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'build.sh'
      - 'build.yml'
  pull_request:
    paths:
      - 'build.sh'
      - 'build.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies & Reflector
        run: |
          pacman -Sy --noconfirm base-devel git sudo nodejs npm reflector
          
          echo "==> Ranking Arch Linux mirrors for fast downloads..."
          reflector --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
          pacman -Syy
          
          echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build user
        run: |
          useradd -m build
          chown -R build:build .

      - name: Run build script
        run: |
          chmod +x build.sh
          su build -c './build.sh'

      - name: Create/Update GitHub Release (latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: output/*.pkg.tar.*
          overwrite_files: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
